name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.KARMARUNNERBOT_GITHUB_TOKEN }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          # Need to upgrade this when upgrading node-saucelabs + wdio
          node-version: "10.x"
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: yarn run-example
